<a href="https://colab.research.google.com/github/MrJames509/Ciencia-de-datos/blob/main/Copia_de_T_P_7_Alumnos_Pandas_Introducci%C3%B3n_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# PANDAS INTRODUCCIÓN
### **Carrera:** Tecnicatura Superior en Ciencia de Datos e IA
### **Institución:** IFTS 33 - UOCRA
### **Profesora:** Marisa Cánovas

##Ejercicio 1 A: El Desafío del Inventario Tecnológico

Contexto: Son Data Scientists en una empresa de tecnología y reciben datos de sensores de 5 servidores distintos. Los datos están crudos en un array de NumPy.

Etapa 1: Construcción "Artesanal" (Manual)
Consigna: Deben crear un DataFrame llamado df_manual utilizando el método de segmentación de un array maestro (Upcasting).

Creen un array de NumPy que contenga en la primera fila los nombres de las columnas y en la primera columna los nombres de las filas.

El array debe tener 5 filas de datos y 3 columnas de datos (sin contar etiquetas).

Restricción: Deben usar data2[1:,1:] para los datos y las posiciones específicas para index y columns.


Etapa 2: Construcción Profesional (Directa)
Consigna: Ahora, utilicen el método más eficiente de Pandas para crear df_profesional usando el array de datos puros y los parámetros data, index y columns en una sola línea.

In [6]:
import numpy as np
import pandas as pd

# 1. Este es el array que deben procesar
datos_it = np.array([
    [95.5, 40, 1.2],
    [88.0, 35, 1.5],
    [np.nan, 42, 2.0],
    [75.2, 38, 1.1],
    [92.1, 45, 1.8]
])

# Etiquetas que DEBEN usar:
columnas = ['CPU_%', 'RAM_%', 'Latencia']
filas = ['Server_A', 'Server_B', 'Server_C', 'Server_D', 'Server_E']

In [7]:
# 1. Creamos la matriz vacía de strings (6 filas x 4 columnas en total)
data2 = np.empty((6, 4), dtype='<U32')

# 2. Asignamos la esquina superior izquierda (vacía o con un placeholder)
data2[0, 0] = ''

# 3. Colocamos los nombres de las columnas en la primera fila
data2[0, 1:] = columnas

# 4. Colocamos los nombres de las filas en la primera columna
data2[1:, 0] = filas

# 5. Insertamos los datos puros en el bloque restante
data2[1:, 1:] = datos_it

# 6. Construimos df_manual segmentando el array maestro según la restricción
df_manual = pd.DataFrame(
    data=data2[1:, 1:],    # Restricción obligatoria: los datos puros
    index=data2[1:, 0],    # Primera columna (nombres de servidores)
    columns=data2[0, 1:]   # Primera fila (nombres de métricas)
)

print("--- DataFrame Manual (Etapa 1) ---")
print(df_manual)

--- DataFrame Manual (Etapa 1) ---
         CPU_% RAM_% Latencia
Server_A  95.5  40.0      1.2
Server_B  88.0  35.0      1.5
Server_C   nan  42.0      2.0
Server_D  75.2  38.0      1.1
Server_E  92.1  45.0      1.8

In [8]:
# Construcción directa y limpia en una sola línea
df_profesional = pd.DataFrame(data=datos_it, index=filas, columns=columnas)

print("\n--- DataFrame Profesional (Etapa 2) ---")
print(df_profesional)

--- DataFrame Profesional (Etapa 2) ---
          CPU_%  RAM_%  Latencia
Server_A   95.5   40.0       1.2
Server_B   88.0   35.0       1.5
Server_C    NaN   42.0       2.0
Server_D   75.2   38.0       1.1
Server_E   92.1   45.0       1.8

##Ejercicio 1 B  Descifrando el Dataset

Instrucciones: Utilizando el DataFrame df_profesional que acaban de crear, ejecuten los siguientes comandos, uno por uno. Su tarea es observar el resultado y averiguar para qué sirve cada función en el análisis de datos.

df_profesional.head(2)

df_........tail(2)

df_.......sample(2)

df_........info()

df_.......describe()

df_........shape

df_.......columns

df_.......index

df_........isnull().sum()

df_........sort_values(by='CPU_%', ascending=False)

##Ejercicio 2: Primer contacto con los datos

Consigna: Mostrá las primeras 3 filas del DataFrame obras_activas

In [9]:
import pandas as pd

# --- PREPARACIÓN DE DATOS (No modificar esta parte) ---
datos_obras = {
    'Ubicación': ['Av. Rivadavia 4500', 'Paraguay 1200', 'Av. Corrientes 3200', 'Altolaguirre 2100', 'Av. San Martín 1500'],
    'Capataz': ['González', 'Martínez', 'Rodríguez', 'López', 'González'],
    'Presupuesto_ARS': [15000000, 28000000, 45000000, 12500000, 32000000],
    'Estado': ['Inicio', 'Techado', 'Terminaciones', 'Cimientos', 'Techado'],
    'Fecha_Fin': [None, '2026-10-15', None, '2027-01-20', '2026-12-01']
}
obras_activas = pd.DataFrame(datos_obras)
obras_activas.head(3)

             Ubicación    Capataz  Presupuesto_ARS         Estado   Fecha_Fin
0   Av. Rivadavia 4500   González         15000000         Inicio        None
1        Paraguay 1200   Martínez         28000000        Techado  2026-10-15
2  Av. Corrientes 3200  Rodríguez         45000000  Terminaciones        None

##Ejercicio 3: Selección de columnas específicas

Consigna: El área de administración solo necesita un listado con las direcciones y quién está a cargo. Seleccioná y mostrá las columnas 'Ubicación' y 'Capataz'

In [10]:
# Escribí tu código aquí:
obras_activas[['Ubicación', 'Capataz']]

             Ubicación    Capataz
0   Av. Rivadavia 4500   González
1        Paraguay 1200   Martínez
2  Av. Corrientes 3200  Rodríguez
3    Altolaguirre 2100      López
4  Av. San Martín 1500   González

##Ejercicio 4: Filtrado por presupuesto

Consigna: Queremos identificar las obras de mayor envergadura. Filtrá el DataFrame para mostrar solo aquellas obras cuyo 'Presupuesto_ARS' sea mayor a 20.000.000

In [11]:
# Escribí tu código aquí:
obras_activas[obras_activas['Presupuesto_ARS'] > 20000000]

             Ubicación    Capataz  Presupuesto_ARS         Estado   Fecha_Fin
1        Paraguay 1200   Martínez         28000000        Techado  2026-10-15
2  Av. Corrientes 3200  Rodríguez         45000000  Terminaciones        None
4  Av. San Martín 1500   González         32000000        Techado  2026-12-01

##Ejercicio 5 EL FILTRO DEL JEFE:

Mostrá solo las obras que están en estado "Techado"

In [12]:
# Escribí tu código aquí:
obras_activas[obras_activas['Estado'] == 'Techado']

             Ubicación   Capataz  Presupuesto_ARS   Estado   Fecha_Fin
1        Paraguay 1200  Martínez         28000000  Techado  2026-10-15
4  Av. San Martín 1500  González         32000000  Techado  2026-12-01

##Ejercicio 6: El Presupuesto Más Alto

Consigna: Para el planeamiento de riesgos, el director de obra necesita saber cuál es el presupuesto más elevado de todo el listado. Utilizá la función correspondiente para encontrar el valor máximo de la columna 'Presupuesto_ARS'

In [13]:
# Escribí tu código aquí:
obras_activas['Presupuesto_ARS'].max()

45000000

##Ejercicio 7: A: Selección por Posición (iloc)

Consigna: El capataz de la última obra de la lista quiere ver sus datos. Usá .iloc para seleccionar y mostrar la información de la fila que está en la última posición (índice 4).

In [14]:
# Escribí tu código aquí:
obras_activas.iloc[4]

Ubicación          Av. San Martín 1500
Capataz                       González
Presupuesto_ARS               32000000
Estado                         Techado
Fecha_Fin                   2026-12-01
Name: 4, dtype: object

##Ejercicio 7.B: Selección por Etiqueta (loc)

Consigna: Ahora vamos a usar .loc para traer un dato puntual. De la obra que tiene la etiqueta de índice 2, mostrá solamente su 'Ubicación'.

In [15]:
# Escribí tu código aquí:
obras_activas.loc[2, 'Ubicación']

'Av. Corrientes 3200'