<a href="https://colab.research.google.com/github/MrJames509/Ciencia-de-datos/blob/main/Operaciones_b%C3%A1sicas_Pandas__2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# PANDAS OPERACIONES BÁSICAS II
### **Carrera:** Tecnicatura Superior en Ciencia de Datos e IA
### **Institución:** IFTS 33 - UOCRA
### **Profesora:** Marisa Cánovas

In [ ]:
import numpy as np
import pandas as pd

## Indexación y slicing en pandas

Pandas pone a nuestra disposición nuevos métodos de indexación que permiten tener un mayor control sobre la misma y superar las limitaciones que nos impone NumPy sobre este tipo de estructuras.

Aclaración:

Indexar = Quiero el dato que está en esta dirección.La indexación es el mecanismo para acceder a un dato que ya sabés dónde está.

Filtrar = Quiero los datos que cumplan esta condición.El filtrado es cuando no sabés en qué fila está el dato, pero sabés qué característica tiene que cumplir

Slicing= Mientras que la indexación común suele ser para buscar un "punto" (un valor específico), el slicing se usa para obtener un segmento o tajada de la estructura.


Veamos todas las posibles combinaciones.<br/>

### Indexación por atributo de clave

Podemos indexar un elemento concreto de una Serie o una columna concreta de un DataFrame mediante el uso de su etiqueta/clave como atributo, con sintaxis obj.etiqueta.

In [ ]:
serie = pd.Series([1, 2, 3, 4], index = ['a', 'b', 'c', 'd'])
serie['a']

np.int64(1)

##Etiqueta

In [ ]:
serie.a

np.int64(1)

In [ ]:
serie["a"]

np.int64(1)

In [ ]:
serie[["a", "b"]]

a    1
b    2
dtype: int64

In [ ]:
serie[["a", "b", "c"]]

a    1
b    2
c    3
dtype: int64

##Posición

In [ ]:
serie[0]#  por posición me trae el número pero me  da un warning

/tmp/ipykernel_11187/3788307178.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  serie[0]#  por posición me trae el número pero me  da un warning

np.int64(1)

##iloc   Es posicional: Mira el orden. solo sirve para ver o cambiar lo que ya existe. No podés usarlo para agregar filas nuevas (solo sirve para Update).

In [ ]:
serie.iloc[0]  # Trae el 1 (posición cero)

np.int64(1)

In [ ]:
serie.iloc[[0, 2]]#trae dos valores de dos posiciones

a    1
c    3
dtype: int64

##loc Es nominal: Mira el nombre, si no encuentra la etiqueta, te crea la fila (funciona como un Insert)

In [ ]:
serie.loc['a'] # Trae el 1

np.int64(1)

In [ ]:
serie.loc[['a', 'c']]#trae dos valores a la vez

a    1
c    3
dtype: int64

##Comprobación

In [ ]:
"b" in serie

True

In [ ]:
dataframe = pd.DataFrame(np.arange(16).reshape(4, 4), index=['f1', 'f2', 'f3', 'f4'], columns=['c1','c2','c3','c4'])
dataframe

    c1  c2  c3  c4
f1   0   1   2   3
f2   4   5   6   7
f3   8   9  10  11
f4  12  13  14  15

##Por nombre de columna

In [ ]:
dataframe.c1

f1     0
f2     4
f3     8
f4    12
Name: c1, dtype: int64

In [ ]:
dataframe['c1']

f1     0
f2     4
f3     8
f4    12
Name: c1, dtype: int64

##.loc  incluye todo

In [ ]:
dataframe.loc[:, 'c1']

f1     0
f2     4
f3     8
f4    12
Name: c1, dtype: int64

In [ ]:
dataframe.loc[:, ['c1', 'c2']]

    c1  c2
f1   0   1
f2   4   5
f3   8   9
f4  12  13

##Por columna y fila

In [ ]:
dataframe = pd.DataFrame(np.arange(16).reshape(4, 4), index=['f1', 'f2', 'f3', 'f4'], columns=['c1','c2','c3','c4'])
dataframe

    c1  c2  c3  c4
f1   0   1   2   3
f2   4   5   6   7
f3   8   9  10  11
f4  12  13  14  15

In [ ]:
# Trae el valor 6
dataframe.loc['f2', 'c3']

np.int64(6)

##Varias filas y varias columnas (Submatriz)

In [ ]:
dataframe = pd.DataFrame(np.arange(16).reshape(4, 4), index=['f1', 'f2', 'f3', 'f4'], columns=['c1','c2','c3','c4'])
dataframe

    c1  c2  c3  c4
f1   0   1   2   3
f2   4   5   6   7
f3   8   9  10  11
f4  12  13  14  15

In [ ]:
# Usando listas (doble corchete interno para cada dimensión)
dataframe.loc[['f1', 'f2'], ['c1', 'c4']]

    c1  c4
f1   0   3
f2   4   7

##.loc, recordá que incluye el último valor    incluye todo

In [ ]:
dataframe = pd.DataFrame(np.arange(16).reshape(4, 4), index=['f1', 'f2', 'f3', 'f4'], columns=['c1','c2','c3','c4'])
dataframe

    c1  c2  c3  c4
f1   0   1   2   3
f2   4   5   6   7
f3   8   9  10  11
f4  12  13  14  15

In [ ]:
# Trae de la fila f1 a la f3, y de la columna c2 a la c4
dataframe.loc['f1':'f3', 'c2':'c4']

    c2  c3  c4
f1   1   2   3
f2   5   6   7
f3   9  10  11

##iloc   [Desde : Hasta). Es decir, el primero se incluye, pero el **último se queda afuera.**

##Un solo valor (Cruce exacto)

In [ ]:
dataframe = pd.DataFrame(np.arange(16).reshape(4, 4), index=['f1', 'f2', 'f3', 'f4'], columns=['c1','c2','c3','c4'])
dataframe

    c1  c2  c3  c4
f1   0   1   2   3
f2   4   5   6   7
f3   8   9  10  11
f4  12  13  14  15

In [ ]:
# Fila 1, Columna 2
dataframe.iloc[1, 2]

np.int64(6)

In [ ]:
dataframe = pd.DataFrame(np.arange(16).reshape(4, 4), index=['f1', 'f2', 'f3', 'f4'], columns=['c1','c2','c3','c4'])
dataframe

    c1  c2  c3  c4
f1   0   1   2   3
f2   4   5   6   7
f3   8   9  10  11
f4  12  13  14  15

In [ ]:
# Usamos listas de números  #fila 0 y 2 y columnas  1 y 3
dataframe.iloc[[0, 2], [1, 3]]

    c2  c4
f1   1   3
f3   9  11

##Varias posiciones específicas (Salteadas)

In [ ]:
dataframe = pd.DataFrame(np.arange(16).reshape(4, 4), index=['f1', 'f2', 'f3', 'f4'], columns=['c1','c2','c3','c4'])
dataframe

    c1  c2  c3  c4
f1   0   1   2   3
f2   4   5   6   7
f3   8   9  10  11
f4  12  13  14  15

In [ ]:
# Usamos listas de números
dataframe.iloc[[0, 2], [1, 3]]

    c2  c4
f1   1   3
f3   9  11

##Usando Rangos (Slicing numérico)

In [ ]:
dataframe = pd.DataFrame(np.arange(16).reshape(4, 4), index=['f1', 'f2', 'f3', 'f4'], columns=['c1','c2','c3','c4'])
dataframe

    c1  c2  c3  c4
f1   0   1   2   3
f2   4   5   6   7
f3   8   9  10  11
f4  12  13  14  15

In [ ]:
# Recordá que el límite derecho (2 o 4) no se incluye  Se incluye el primero pero el ultimo queda afuera
dataframe.iloc[0:2, 2:4]

    c3  c4
f1   2   3
f2   6   7

## Índices jerárquicos en pandas

Los índices jerárquicos de 'pandas' permiten tener más de un nivel en cualquiera de los índices de una estructura. Esto puede servir para agrupar más claramente los datos, o para conseguir identificar las filas por una clave única. En cierto modo, también es una forma de poder trabajar con tablas de más de dos dimensiones.

In [ ]:
peliculas = pd.DataFrame(
            {'Valoración':[6, None, 8.75, None],
             'Presupuesto':[160, 250, 100, None],
             'Director':['Peter Jackson', 'Gareth Edwards', 'Martin Scorsese', 'Alfonso Cuarón']},
            index = [[2014, 2014, 2013, 2013], ['Godzilla', 'El Hobbit III', 'El lobo de Wall Street', 'Gravity']]
)
peliculas

                             Valoración  Presupuesto         Director
2014 Godzilla                      6.00        160.0    Peter Jackson
     El Hobbit III                  NaN        250.0   Gareth Edwards
2013 El lobo de Wall Street        8.75        100.0  Martin Scorsese
     Gravity                        NaN          NaN   Alfonso Cuarón

A partir de la construcción del índice jerárquico, podemos hacer indexaciones totales (mediante tuplas) o parciales (mediante selección de uno de los elementos del índice).

In [ ]:
# Indexación total
peliculas.loc[(2014, 'Godzilla')]

Valoración               6.0
Presupuesto            160.0
Director       Peter Jackson
Name: (2014, Godzilla), dtype: object

In [ ]:
# Indexación parcial
peliculas.loc[2014]

               Valoración  Presupuesto        Director
Godzilla              6.0        160.0   Peter Jackson
El Hobbit III         NaN        250.0  Gareth Edwards

Podemos pasar niveles del índice jerárquico de las filas a las columnas mediante la función <b>unstack</b>, como si de una Pivot Table de Excel se tratase. El efecto: El DataFrame se hace más "bajo" y más ancho.

Con <b>stack</b> realizarmeos la operación contraria.

In [ ]:
peliculas

                             Valoración  Presupuesto         Director
2014 Godzilla                      6.00        160.0    Peter Jackson
     El Hobbit III                  NaN        250.0   Gareth Edwards
2013 El lobo de Wall Street        8.75        100.0  Martin Scorsese
     Gravity                        NaN          NaN   Alfonso Cuarón

In [ ]:
# Pasamos el último nivel del índice de filas al de columnas
#peliculas_2 = peliculas.unstack()
# Rellenamos los NaNs con un guión o un cero para que no molesten visualmente
peliculas_2 = peliculas.unstack().fillna('-')
peliculas_2

        Valoración                                           Presupuesto  \
     El Hobbit III El lobo de Wall Street Godzilla Gravity El Hobbit III
2013             -                   8.75        -       -             -
2014             -                      -      6.0       -         250.0

                                                    Director  \
     El lobo de Wall Street Godzilla Gravity   El Hobbit III
2013                  100.0        -       -               -
2014                      -    160.0       -  Gareth Edwards


     El lobo de Wall Street       Godzilla         Gravity
2013        Martin Scorsese              -  Alfonso Cuarón
2014                      -  Peter Jackson               -

In [ ]:
# La forma "moderna" de hacerlo
peliculas_2.stack(future_stack=True)

                            Valoración Presupuesto         Director
2013 El Hobbit III                   -           -                -
     El lobo de Wall Street       8.75       100.0  Martin Scorsese
     Godzilla                        -           -                -
     Gravity                         -           -   Alfonso Cuarón
2014 El Hobbit III                   -       250.0   Gareth Edwards
     El lobo de Wall Street          -           -                -
     Godzilla                      6.0       160.0    Peter Jackson
     Gravity                         -           -                -

In [ ]:
peliculas

                             Valoración  Presupuesto         Director
2014 Godzilla                      6.00        160.0    Peter Jackson
     El Hobbit III                  NaN        250.0   Gareth Edwards
2013 El lobo de Wall Street        8.75        100.0  Martin Scorsese
     Gravity                        NaN          NaN   Alfonso Cuarón

In [ ]:
# Pasa el nivel de las columnas al índice de las filas.
peliculas.stack()

2014  Godzilla                Valoración                 6.0
                              Presupuesto              160.0
                              Director         Peter Jackson
      El Hobbit III           Presupuesto              250.0
                              Director        Gareth Edwards
2013  El lobo de Wall Street  Valoración                8.75
                              Presupuesto              100.0
                              Director       Martin Scorsese
      Gravity                 Director        Alfonso Cuarón
dtype: object

## Modificación de índices en Pandas

En cualquier momento, podemos descartar el índice de un DataFrame incorporando el mismo como una columna más de nuestros datos. Esto lo haremos mediante la función <b>reset_index</b>. Esto hará que el índice pase a ser una secuencia numérica.

In [ ]:
dataframe

    c1  c2  c3  c4
f1   0   1   2   3
f2   4   5   6   7
f3   8   9  10  11
f4  12  13  14  15

In [ ]:
dataframe.reset_index()

  index  c1  c2  c3  c4
0    f1   0   1   2   3
1    f2   4   5   6   7
2    f3   8   9  10  11
3    f4  12  13  14  15

Del mismo modo, podemos reestablecer un conjunto de columnas como índice de un DataFrame con la función <b>set_index</b>.

In [ ]:
dataframe

    c1  c2  c3  c4
f1   0   1   2   3
f2   4   5   6   7
f3   8   9  10  11
f4  12  13  14  15

In [ ]:
dataframe.set_index(['c1'])

    c2  c3  c4
c1
0    1   2   3
4    5   6   7
8    9  10  11
12  13  14  15