<a href="https://colab.research.google.com/github/MrJames509/Ciencia-de-datos/blob/main/t_p_11_alumnos__exploraci_n_limpieza_y_an_lisis_de_ventas_en_pandas_l.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# Exploración, Limpieza y Análisis de Ventas en Pandas l
### **Carrera:** Tecnicatura Superior en Ciencia de Datos e IA
### **Institución:** IFTS 33 - UOCRA
### **Profesora:** Marisa Cánovas

##Alcance de la Práctica y Estado del Dataset

Aclaración Inicial: El presente dataset ha sido sometido a un proceso previo de curación y estandarización con fines estrictamente pedagógicos. Al ser este el primer contacto de la materia con la librería Pandas para el análisis de datos tabulares, se ha simplificado la estructura del archivo para priorizar el aprendizaje de la lógica de filtrado y manipulación.

Para el desarrollo de esta práctica, consideren que el dataset ya cuenta con las siguientes condiciones optimizadas:

Formatos Numéricos Puros: Las variables cuantitativas (como los montos de dinero) se presentan libres de caracteres especiales, símbolos monetarios ($) o separadores de texto, permitiendo su conversión directa.

Consistencia en Fechas: Los campos temporales se encuentran normalizados, omitiendo la necesidad actual de parseo o conversión de formatos de texto a tipo cronológico (datetime).

Integridad de Registros: El archivo no presenta registros duplicados ni inconsistencias críticas en sus variables nominales y categóricas.

Tratamiento Controlado de Vacíos: Si bien el dataset preserva sus valores faltantes (NaN) nativos, la gestión avanzada y la imputación estadística de los mismos se abordarán en la siguiente unidad.

###Carga del Dataset

Para comenzar a trabajar, ejecuten el código para importar las librerías necesarias y cargar el archivo ventas.csv de manera automática desde la carpeta de Descargas de sus computadoras o para pedir  permiso al drive para leer desde allí el archivo.

###PASO 1: Exploración Inicial del Dataset

Consignas: Ejecuten los comandos necesarios para resolver los siguientes puntos, uno abajo del otro:

A: Averigüen la cantidad total de filas y columnas de la tabla original.

B: Inspeccionen los tipos de datos asignados a cada columna.

C: Investiguen la presencia de nulos: Averigüen cuántos valores faltantes (NaN) tiene cada una de las columnas del dataset.

D: Obtengan la descripción estadística de las columnas numéricas de forma vertical.

E: Visualicen únicamente las últimas 7 filas del archivo.

F: Registren la cantidad de valores reales (no nulos) que tiene la columna Importe.

G: Averigüen cuántos valores únicos (no repetidos) existen en la columna Importe.

H: Cuenten cuántas filas están exactamente repetidas (duplicadas) en todo el dataset.

I: Agregue otra exploración que le parezca pertinente

###PASO 2: Estandarización de Variables Financieras

Consignas: Ejecuten las acciones necesarias para resolver los siguientes puntos de forma consecutiva:

A: Transformen permanentemente las columnas Importe y Comision_x_venta a tipo decimal (float).

B: Verifiquen que el cambio se haya aplicado correctamente volviendo a inspeccionar los tipos de datos de la tabla.

C: Para responder: Justifiquen conceptualmente por qué la columna Satisfaccion_cliente debe quedar intacta como tipo entero (int).

###PASO 3: Formato Estético de Visualización

Consignas: Ejecuten las acciones necesarias para resolver los siguientes puntos de forma consecutiva:

A: Configuren Pandas de forma global para que todos los números decimales (float) se muestren en pantalla con formato de dinero (agregando el signo $ y dos decimales).

B: Visualicen las primeras 5 filas de la columna Importe para verificar que el cambio visual se aplicó correctamente

###PASO 4: Filtrado, Aislamiento Seguro y Slicing por Posición

Consignas: Ejecuten las acciones necesarias para resolver los siguientes puntos de forma consecutiva:

A: Utilicen la estructura .loc para filtrar el dataset original y aislar únicamente las ventas correspondientes al vendedor Mufi Panchin.

B: Aseguren la independencia de este nuevo subconjunto creando una copia explícita en memoria (.copy()) y guárdenlo en una nueva variable llamada mufi.

C: Utilicen .iloc para extraer un extracto (slicing) de la nueva tabla mufi. Necesitamos visualizar específicamente desde la fila indexada 0 hasta la 9 inclusive, y traer únicamente las columnas de Rubro e Importe.

D: Para responder: Expliquen qué riesgo corremos si olvidamos aplicar la función .copy() al momento de segmentar un DataFrame

###PASO 5: Simulación y Auditoría de Valores Faltantes

Consignas: Trabajando sobre la tabla de mufi, ejecuten las siguientes acciones una abajo de la otra:

A: Utilicen .loc para reemplazar por un valor vacío (None) el importe de todas aquellas ventas que sean inferiores a $350.000. (¡Importante! Hagan esto directamente sobre la tabla mufi para que este "bache" de datos quede simulado para el resto del trabajo).

B: Ejecuten el comando de auditoría general que cuenta cuántos valores nulos (NaN) hay en cada columna de la tabla para verificar exactamente en cuál de ellas impactó el cambio.

C: Utilicen la función .count() específicamente sobre la columna Importe y comparen ese resultado numérico con el tamaño total de la tabla obtenido mediante len(mufi).

D: Para responder: Expliquen por qué el resultado de .count() difiere de len() tras haber realizado el reemplazo del punto A.

🧠 Antes de avanzar: ¿Qué hace realmente .dropna()?

Es súper común confundirse y pensar que .dropna() borra columnas enteras o datos válidos. ¡Para nada! El comando .dropna() siempre busca eliminar únicamente las FILAS que contienen valores vacíos (NaN o None).


La clave está en si usamos o no el argumento subset:


1. Si NO usamos subset ➡️ mufi.dropna() Le decimos a Python: "Mirá TODA la tabla. Si una fila tiene un vacío en el Importe, o en el Vendedor, o en la Satisfacción... donde sea... ¡me borrás la fila entera!".

⚠️ Peligro: Podés terminar borrando una fila con una venta real de $2.000.000 solo porque el cliente se olvidó de poner una puntuación en la columna de satisfacción.

2. Si SÍ usamos subset ➡️ mufi.dropna(subset=['Importe']) Le ponemos filtro a Pandas y le decimos: "Mirá ÚNICAMENTE la columna Importe. Si encontrás un vacío ahí, borrá la fila entera. Si hay un número real (como los mayores a $350.000), la fila SE QUEDA intacta. Y si hay vacíos en otras columnas... ¡ignoralos!".


📌 En resumen: Los números reales mayores a $350.000 no se borran jamás. El subset solo le avisa a Python en qué columna tiene que mirar para buscar los baches antes de decidir si elimina la fila o no.

###PASO 6: Estrategias ante la Pérdida de Datos

Consignas: Evalúen el impacto de limpiar los datos vacíos que generaron en el paso anterior, ejecutando las siguientes acciones:

A: Apliquen el método para rellenar de forma masiva únicamente los valores faltantes (NaN) de la columna Importe en la tabla mufi con el número 0. (¡Ojo! Guarden este resultado en una nueva variable llamada mufi_rellenado para no perder los nulos de la original).

B: En una celda aparte (usando la tabla mufi original que todavía contiene los nulos), utilicen el comando para eliminar por completo las filas que tengan un valor vacío en la columna Importe. Guarden el resultado en una variable llamada mufi_sin_nulos.

C: Para responder: Desde la perspectiva del negocio, ¿cuál es el peligro de rellenar los importes vacíos con 0 a ciegas en lugar de eliminar esas filas?

In [1]:
import pandas as pd
import os

# Opción 1: Cargar desde la carpeta de Descargas (ejecutando en tu compu local)
ruta_descargas = os.path.expanduser("/content/ventas.csv")
df = pd.read_csv(ruta_descargas)

# Opción 2: Cargar desde Google Drive (si trabajás en Colab)
# from google.colab import drive


df.head()

,Fecha,Vendedor,Sede,Rubro,Marca,Importe,Comision_x_venta,Satisfaccion_cliente
0,10/02/2022,Juliet Glynne,Paternal,equipos de video,Wacom,381291,17243,10
1,17/02/2022,Mufi Panchin,Ezeiza,notebook,Samsung,111535,16691,7
2,14/04/2022,Constantine Creeber,Villa Bosch,equipos de video,Kensington,418512,20934,4
3,23/03/2022,Pennie Hess,Palermo,TV,Engel,236222,17952,9
4,28/03/2022,Timmy Ashlin,Villa Crespo,electrodomésticos,Kensington,266683,18070,7

In [3]:
df.shape

(1000, 8)

In [4]:
df.dtypes

Fecha                   object
Vendedor                object
Sede                    object
Rubro                   object
Marca                   object
Importe                  int64
Comision_x_venta         int64
Satisfaccion_cliente     int64
dtype: object

In [5]:
df.isnull().sum()

Fecha                   0
Vendedor                0
Sede                    0
Rubro                   0
Marca                   0
Importe                 0
Comision_x_venta        0
Satisfaccion_cliente    0
dtype: int64

In [6]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Importe,1000.0,280639.599,104057.141562,99569.0,188740.25,284569.0,368610.75,458943.0
Comision_x_venta,1000.0,20943.965,2585.770183,16538.0,18673.75,20921.5,23116.25,25551.0
Satisfaccion_cliente,1000.0,6.483,2.277476,3.0,5.00,6.0,8.00,10.0

In [7]:
df.tail(7)

,Fecha,Vendedor,Sede,Rubro,Marca,Importe,Comision_x_venta,Satisfaccion_cliente
993,27/04/2022,Cecil Apted,Avellaneda,equipos de video,Ubiquity,264471,19787,9
994,19/04/2022,Cecil Apted,Ezpeleta,equipos de audio,Huawei,120654,16696,8
995,30/01/2022,Angelita Lambkin,San Nicolás,equipos de video,Access,163927,20933,4
996,28/05/2022,Em Edmonson,Floresta,equipos de video,Ubiquity,368788,20758,5
997,13/02/2022,Arvin Bernhardi,Boedo,equipos de video,LG,258935,21330,10
998,31/01/2022,Humfried Woodberry,San Martín,TV,Millenium,395583,17743,3
999,18/05/2022,Barde Benoist,Ezeiza,notebook,Xiaomi,313634,23430,9

In [8]:
df['Importe'].count()

np.int64(1000)

In [9]:
df['Importe'].nunique()

998

In [10]:
df.duplicated().sum()

np.int64(0)

In [11]:
# Info general del dataset: tipos, no-nulos y uso de memoria en un solo vistazo
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Fecha                 1000 non-null   object
 1   Vendedor              1000 non-null   object
 2   Sede                  1000 non-null   object
 3   Rubro                 1000 non-null   object
 4   Marca                 1000 non-null   object
 5   Importe               1000 non-null   int64
 6   Comision_x_venta      1000 non-null   int64
 7   Satisfaccion_cliente  1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

# **Paso 2**

In [12]:
df['Importe'] = df['Importe'].astype(float)
df['Comision_x_venta'] = df['Comision_x_venta'].astype(float)

In [14]:
df.dtypes

Fecha                    object
Vendedor                 object
Sede                     object
Rubro                    object
Marca                    object
Importe                 float64
Comision_x_venta        float64
Satisfaccion_cliente      int64
dtype: object

La columna Satisfaccion_cliente representa una escala discreta, probablemente valores como 1, 2, 3, 4, 5 (por ejemplo, una calificación de 1 a 5 estrellas). Estos valores:

No admiten fracciones o decimales en su naturaleza conceptual: no existe una satisfacción de "3.7", tiene sentido lógico solo como número entero.
Son categorías ordenadas, no mediciones continuas como el dinero (que sí puede tener centavos).
Mantenerla como int refleja fielmente el diseño original de la variable y evita sugerir una precisión que el dato no tiene.

# Paso 3

In [16]:
pd.options.display.float_format = '${:,.2f}'.format

In [17]:
df['Importe'].head()

0   $381,291.00
1   $111,535.00
2   $418,512.00
3   $236,222.00
4   $266,683.00
Name: Importe, dtype: float64

# Paso 4

In [18]:
df.loc[df['Vendedor'] == 'Mufi Panchin']

,Fecha,Vendedor,Sede,Rubro,Marca,Importe,Comision_x_venta,Satisfaccion_cliente
1,17/02/2022,Mufi Panchin,Ezeiza,notebook,Samsung,"$111,535.00","$16,691.00",7
5,14/02/2022,Mufi Panchin,Villa Crespo,equipos de video,Nord,"$127,348.00","$23,521.00",7
18,12/06/2022,Mufi Panchin,Paternal,equipos de video,Synology,"$123,809.00","$24,915.00",5
69,31/03/2022,Mufi Panchin,Palermo,equipos de video,Xiaomi,"$409,249.00","$22,388.00",8
81,31/05/2022,Mufi Panchin,Recoleta,notebook,Belkin,"$428,778.00","$19,145.00",7
...,...,...,...,...,...,...,...,...
862,04/05/2022,Mufi Panchin,Chacarita,equipos de video,Vodafone,"$400,679.00","$22,697.00",3
875,17/02/2022,Mufi Panchin,San Martín,PC armada,Netgear,"$188,894.00","$17,534.00",5
878,27/04/2022,Mufi Panchin,Boedo,PC armada,Huawei,"$451,575.00","$23,051.00",8
907,03/05/2022,Mufi Panchin,San Nicolás,equipos de video,Access,"$256,406.00","$22,956.00",9
980,19/01/2022,Mufi Panchin,Recoleta,PC armada,Xiaomi,"$265,057.00","$23,069.00",9

In [19]:
mufi = df.loc[df['Vendedor'] == 'Mufi Panchin'].copy()

In [20]:
mufi.iloc[0:10, mufi.columns.get_indexer(['Rubro', 'Importe'])]

                 Rubro     Importe
1             notebook $111,535.00
5     equipos de video $127,348.00
18    equipos de video $123,809.00
69    equipos de video $409,249.00
81            notebook $428,778.00
97    equipos de audio $412,488.00
102   equipos de audio $162,204.00
116  electrodomésticos $341,082.00
132                 TV $173,532.00
143          PC armada $127,575.00

Si no usás .copy(), la variable mufi no es una tabla nueva e independiente. Es solo una vista (referencia) que apunta a los mismos datos que df. Esto genera dos problemas:

Si más adelante modificás algo en mufi (por ejemplo, cambiás un valor en una celda), corrés el riesgo de modificar también el df original sin querer, porque ambos "apuntan" a la misma memoria.
Pandas suele mostrar una advertencia llamada SettingWithCopyWarning, que avisa que no está claro si estás trabajando sobre una copia o sobre el original. Esto genera comportamiento impredecible: a veces modifica el original, a veces no.

# Paso 5

In [21]:
mufi.loc[mufi['Importe'] < 350000, 'Importe'] = None

In [22]:
mufi.isnull().sum()

Fecha                    0
Vendedor                 0
Sede                     0
Rubro                    0
Marca                    0
Importe                 45
Comision_x_venta         0
Satisfaccion_cliente     0
dtype: int64

In [24]:
mufi['Importe'].count()
len(mufi)

66

len(mufi) cuenta todas las filas de la tabla, sin importar si tienen datos o no. Es el tamaño total.
.count() cuenta solo los valores reales, no nulos, de una columna específica. Ignora los NaN.

# Paso 6

In [25]:
mufi_rellenado = mufi.copy()
mufi_rellenado['Importe'] = mufi_rellenado['Importe'].fillna(0)

In [26]:
mufi_sin_nulos = mufi.dropna(subset=['Importe'])

Rellenar con 0 significa decirle a Pandas "esta venta valió cero pesos". Pero eso es mentira: el valor real no era cero, simplemente no lo teníamos (era un dato faltante). Esto genera un problema serio para el negocio: