<a href="https://colab.research.google.com/github/MrJames509/Ciencia-de-datos/blob/main/t_p_10_alumnos_operaciones_b_sicas_pandas_iii.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


# PANDAS OPERACIONES BÁSICAS III
### **Carrera:** Tecnicatura Superior en Ciencia de Datos e IA
### **Institución:** IFTS 33 - UOCRA
### **Profesora:** Marisa Cánovas

## Actividades Prácticas Integradoras


Para poner a prueba todo lo aprendido en este Notebook sobre gestión de índices, operaciones alineadas y ordenamiento, resuelvan los siguientes desafíos utilizando el DataFrame de películas.

---

###  Actividad 1: El Tablero de Control de Taquilla

El departamento de finanzas nos pasó la lista con los datos de **Recaudación** (en millones) de las 5 películas de nuestro DataFrame, en el mismo orden en que están registradas:
`[400, 850, 300, 1100, 950]`

El director de la empresa nos pide un reporte limpio que cruce a los **Directores** (en las filas) y los **Años** (en las columnas), pero esta vez quiere analizar la **Recaudación total** obtenida.

Resuelvan los siguientes puntos en una sola celda de código:
1. Generen la tabla dinámica utilizando `pd.pivot_table()`.
2. Asegúrense de que si un director tiene más de una película el mismo año, el sistema **sume** las recaudaciones de forma nativa y optimizada (¡eviten que aparezca el cartel amarillo de aviso!).
3. Para que el reporte quede visualmente impecable para los ejecutivos, hagan que todos los casilleros vacíos (`NaN`) se muestren con un guion medio (`"-"`) en lugar de dejar el error a la vista.

Importante para tener en cuenta. Recuerden que posteriormente vamos a utilizar esta tabla dinámica resultante para generar reportes visuales y gráficos. Piensen bien si necesitan guardar el resultado en una variable o si alcanza con solo mostrarlo en pantalla.
---

###  Actividad 2: Jugando con los Ejes y el Ordenamiento

A partir de la tabla dinámica de Recaudación por Director y Año:

1. **Orden por Índices:** Utilicen el método para reordenar las **columnas** (los años) de forma cronológica. ¿Qué valor debe tomar el argumento `axis`? Asegúrense de que el cambio persista en la memoria.
2. **Orden por Índices Inversos:** Sobre ese mismo resultado, ordenen las **filas** (los nombres de los Directores) de forma alfabética inversa (de la Z a la A).
3. **Orden por Valores:** Ahora, ordenen las filas (Directores) según los valores de la columna del año 2014 de mayor a menor. *(Atención: para este punto, utilicen la tabla rellenada con ceros usando `fill_value=0`)*.
4. **Análisis:** Expliquen este comportamiento con sus propias palabras. ¿Se ordenaron los números de las celdas de forma independiente o se movieron las filas completas? ¿Qué pasó con los directores que tenían un `0` en 2014?

###Actividad 3: Operaciones al Límite (¡Viaje al Infinito!)

Imaginemos que tenemos dos Series que representan las salas disponibles en dos complejos de cine distintos para las mismas películas:


complejo_A = pd.Series([2, 4, 0], index=['Peli_1', 'Peli_2', 'Peli_3'])

complejo_B = pd.Series([1, 2], index=['Peli_1', 'Peli_2']) (La Peli_3 no se proyecta acá)

Realicen la división de complejo_A.div(complejo_B, fill_value=0).

Analicen el resultado para Peli_3: ¿Qué valor devuelve Pandas?
¿Qué pasa cuando Pandas intenta dividir ese cero nativo de la Serie A por el cero inyectado en la Serie B?

In [1]:
import pandas as pd
import numpy as np

In [2]:
peliculas = pd.DataFrame(
            {'Año':[2014, 2014, 2013, 2013, 2001],
             'Valoración':[6, None, 8.75, None, 8.9],
             'Presupuesto':[160, 250, 100, None, 93],
             'Director':['Gareth Edwards', 'Peter Jackson', 'Martin Scorsese', 'Alfonso Cuarón', 'Peter Jackson'],
             'Título':['Godzilla', 'El Hobbit III', 'El lobo de Wall Street', 'Gravity', 'Lord of the Rings']}
)
peliculas

    Año  Valoración  Presupuesto         Director                  Título
0  2014        6.00        160.0   Gareth Edwards                Godzilla
1  2014         NaN        250.0    Peter Jackson           El Hobbit III
2  2013        8.75        100.0  Martin Scorsese  El lobo de Wall Street
3  2013         NaN          NaN   Alfonso Cuarón                 Gravity
4  2001        8.90         93.0    Peter Jackson       Lord of the Rings

In [4]:
peliculas['Recaudacion'] = [400, 850, 300, 1100, 950]

In [5]:
# Generamos y guardamos la tabla dinámica según los requisitos
tabla_taquilla = pd.pivot_table(
    peliculas,
    values='Recaudacion',
    index='Director',
    columns='Año',
    aggfunc='sum',
    fill_value="-"
)

# Mostramos el resultado en pantalla
tabla_taquilla

Año             2001  2013 2014
Director
Alfonso Cuarón     -  1100    -
Gareth Edwards     -     -  400
Martin Scorsese    -   300    -
Peter Jackson    950     -  850

In [6]:
# Generamos y guardamos la tabla dinámica según los requisitos
tabla_taquilla = pd.pivot_table(
    peliculas,
    values='Recaudacion',
    index='Director',
    columns='Año',
    aggfunc='sum',
    fill_value="-"
)

# Mostramos el resultado en pantalla
tabla_taquilla

Año             2001  2013 2014
Director
Alfonso Cuarón     -  1100    -
Gareth Edwards     -     -  400
Martin Scorsese    -   300    -
Peter Jackson    950     -  850

In [7]:
# 1. Ordenar columnas cronológicamente (Eje de columnas = 1)
tabla_taquilla.sort_index(axis=1, inplace=True)

# 2. Ordenar filas de la Z a la A (Eje de filas = 0)
tabla_ordenada_z_a = tabla_taquilla.sort_index(axis=0, ascending=False)
tabla_ordenada_z_a

Año             2001  2013 2014
Director
Peter Jackson    950     -  850
Martin Scorsese    -   300    -
Gareth Edwards     -     -  400
Alfonso Cuarón     -  1100    -

In [8]:
# Volvemos a generar la tabla pivot pero con ceros para poder ordenar numéricamente
tabla_ceros = pd.pivot_table(
    peliculas,
    values='Recaudacion',
    index='Director',
    columns='Año',
    aggfunc='sum',
    fill_value=0
)

# Ordenamos las filas según la columna del año 2014 de mayor a menor
tabla_por_2014 = tabla_ceros.sort_values(by=2014, ascending=False)
tabla_por_2014

Año              2001  2013  2014
Director
Peter Jackson     950     0   850
Gareth Edwards      0     0   400
Alfonso Cuarón      0  1100     0
Martin Scorsese     0   300     0

In [9]:
complejo_A = pd.Series([2, 4, 0], index=['Peli_1', 'Peli_2', 'Peli_3'])
complejo_B = pd.Series([1, 2], index=['Peli_1', 'Peli_2'])

# Realizamos la división con fill_value=0
resultado_div = complejo_A.div(complejo_B, fill_value=0)
resultado_div

Peli_1    2.0
Peli_2    2.0
Peli_3    NaN
dtype: float64